# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/JonnyDabestPlots',
                'doc_host': 'https://JAnns98.github.io',
                'git_url': 'https://github.com/JAnns98/JonnyDabestPlots',
                'lib_path': 'JonnyDabestPlots'},
  'syms': {'JonnyDabestPlots.core': {'JonnyDabestPlots.core.foo': ('core.html#foo', 'JonnyDabestPlots/core.py')}}}
